crop_recommendations = {
    'rice': {
        'soil_type': ['Clayey', 'Loamy'],
        'soil_ph': {'min': 5.0, 'max': 6.5},
        'soil_nutrients': {'N': 100, 'P': 60, 'K': 60},
        'temperature_range': {'min': 20, 'max': 35},
        'annual_rainfall_mm': "1200, 1500",
        'water_ph': {'min': 5.5, 'max': 6.5},
        'sunlight_hours_per_day': "6, 8",
        'humidity_range_percent': {'min': 70, 'max': 90},
        'altitude_m': "0, 1500",
        'wind_conditions_kmh': {'speed': 5, 'direction': 'Variable'}
    },
    'wheat': {
        'soil_type': ['Loamy'],
        'soil_ph': {'min': 6.0, 'max': 7.0},
        'soil_nutrients': {'N': 50, 'P': 30, 'K': 40},
        'temperature_range': {'min': 10, 'max': 25},
        'annual_rainfall_mm': {'min': 500, 'max': 750},
        'water_ph': {'min': 6.5, 'max': 7.5},
        'sunlight_hours_per_day': 8,
        'humidity_range_percent': {'min': 40, 'max': 70},
        'altitude_m': {'min': 0, 'max': 1000},
        'wind_conditions_kmh': {'speed': 5, 'direction': 'N'}
    },
    'maize': {
        'soil_type': ['Loamy', 'Sandy'],
        'soil_ph': {'min': 5.8, 'max': 7.0},
        'soil_nutrients': {'N': 80, 'P': 40, 'K': 60},
        'temperature_range': {'min': 18, 'max': 27},
        'annual_rainfall_mm': {'min': 500, 'max': 800},
        'water_ph': {'min': 6.0, 'max': 7.0},
        'sunlight_hours_per_day': "8, 10",
        'humidity_range_percent': {'min': 50, 'max': 70},
        'altitude_m': {'min': 0, 'max': 2000},
        'wind_conditions_kmh': {'speed': 5, 'direction': 'Variable'}
    },
    'barley': {
        'soil_type': ['Loamy', 'Sandy'],
        'soil_ph': {'min': 6.0, 'max': 7.5},
        'soil_nutrients': {'N': 60, 'P': 30, 'K': 50},
        'temperature_range': {'min': 10, 'max': 24},
        'annual_rainfall_mm': {'min': 500, 'max': 600},
        'water_ph': {'min': 6.0, 'max': 7.5},
        'sunlight_hours_per_day': "8, 10",
        'humidity_range_percent': {'min': 40, 'max': 70},
        'altitude_m': {'min': 0, 'max': 2000},
        'wind_conditions_kmh': {'speed': 5, 'direction': 'N'}
    },
    'sorghum': {
        'soil_type': ['Loamy', 'Sandy'],
        'soil_ph': {'min': 5.5, 'max': 7.5},
        'soil_nutrients': {'N': 40, 'P': 20, 'K': 40},
        'temperature_range': {'min': 25, 'max': 30},
        'annual_rainfall_mm': {'min': 400, 'max': 600},
        'water_ph': {'min': 6.0, 'max': 7.5},
        'sunlight_hours_per_day': "8, 10",
        'humidity_range_percent': {'min': 50, 'max': 70},
        'altitude_m': {'min': 0, 'max': 2000},
        'wind_conditions_kmh': {'speed': 5, 'direction': 'E'}
    },
    'millet': {
        'soil_type': ['Sandy', 'Loamy'],
        'soil_ph': {'min': 5.5, 'max': 7.0},
        'soil_nutrients': {'N': 30, 'P': 20, 'K': 30},
        'temperature_range': {'min': 25, 'max': 30},
        'annual_rainfall_mm': {'min': 300, 'max': 600},
        'water_ph': {'min': 5.5, 'max': 7.0},
        'sunlight_hours_per_day': "8, 10",
        'humidity_range_percent': {'min': 50, 'max': 70},
        'altitude_m': {'min': 0, 'max': 1500},
        'wind_conditions_kmh': {'speed': 5, 'direction': 'Variable'}
    },
    'rye': {
        'soil_type': ['Loamy', 'Sandy'],
        'soil_ph': {'min': 5.5, 'max': 7.0},
        'soil_nutrients': {'N': 50, 'P': 30, 'K': 40},
        'temperature_range': {'min': 8, 'max': 22},
        'annual_rainfall_mm': {'min': 500, 'max': 700},
        'water_ph': {'min': 6.0, 'max': 7.5},
        'sunlight_hours_per_day': "8, 10",
        'humidity_range_percent': {'min': 40, 'max': 70},
        'altitude_m': {'min': 0, 'max': 2000},
        'wind_conditions_kmh': {'speed': 5, 'direction': 'W'}
    },
    'oats': {
        'soil_type': ['Loamy', 'Sandy'],
        'soil_ph': {'min': 6.0, 'max': 7.0},
        'soil_nutrients': {'N': 60, 'P': 30, 'K': 40},
        'temperature_range': {'min': 15, 'max': 20},
        'annual_rainfall_mm': {'min': 500, 'max': 600},
        'water_ph': {'min': 6.0, 'max': 7.5},
        'sunlight_hours_per_day': "8, 10",
        'humidity_range_percent': {'min': 50, 'max': 70},
        'altitude_m': {'min': 0, 'max': 2000},
        'wind_conditions_kmh': {'speed': 5, 'direction': 'W'}
    },
        'pulses': {
        'soil_type': ['Loamy', 'Sandy'],
        'soil_ph': {'min': 6.0, 'max': 7.0},
        'soil_nutrients': {'N': 30, 'P': 20, 'K': 30},
        'temperature_range': {'min': 20, 'max': 30},
        'annual_rainfall_mm': {'min': 500, 'max': 700},
        'water_ph': {'min': 6.0, 'max': 7.0},
        'sunlight_hours_per_day': {'min': 6, 'max': 8},
        'humidity_range_percent': {'min': 50, 'max': 70},
        'altitude_m': {'min': 0, 'max': 1500},
        'wind_conditions_kmh': {'speed': 5, 'direction': 'Variable'}
    },
    'bajra': {
        'soil_type': ['Sandy', 'Loamy'],
        'soil_ph': {'min': 5.5, 'max': 7.0},
        'soil_nutrients': {'N': 40, 'P': 20, 'K': 30},
        'temperature_range': {'min': 25, 'max': 35},
        'annual_rainfall_mm': {'min': 300, 'max': 500},
        'water_ph': {'min': 5.5, 'max': 7.0},
        'sunlight_hours_per_day': {'min': 8, 'max': 10},
        'humidity_range_percent': {'min': 50, 'max': 70},
        'altitude_m': {'min': 0, 'max': 1000},
        'wind_conditions_kmh': {'speed': 5, 'direction': 'Variable'}
    },
    'gram': {
        'soil_type': ['Loamy', 'Sandy'],
        'soil_ph': {'min': 6.0, 'max': 7.5},
        'soil_nutrients': {'N': 20, 'P': 20, 'K': 20},
        'temperature_range': {'min': 20, 'max': 30},
        'annual_rainfall_mm': {'min': 300, 'max': 500},
        'water_ph': {'min': 6.0, 'max': 7.5},
        'sunlight_hours_per_day': {'min': 6, 'max': 8},
        'humidity_range_percent': {'min': 40, 'max': 70},
        'altitude_m': {'min': 0, 'max': 1500},
        'wind_conditions_kmh': {'speed': 5, 'direction': 'Variable'}
    },
    'tea': {
        'soil_type': ['Loamy', 'Sandy'],
        'soil_ph': {'min': 4.5, 'max': 5.5},
        'soil_nutrients': {'N': 60, 'P': 40, 'K': 60},
        'temperature_range': {'min': 20, 'max': 30},
        'annual_rainfall_mm': {'min': 2000, 'max': 3000},
        'water_ph': {'min': 4.5, 'max': 5.5},
        'sunlight_hours_per_day': {'min': 6, 'max': 8},
        'humidity_range_percent': {'min': 70, 'max': 90},
        'altitude_m': {'min': 0, 'max': 1500},
        'wind_conditions_kmh': {'speed': 5, 'direction': 'Variable'}
    },
    'apple': {
    'soil_type': ['Loamy'],
    'soil_ph': {'min': 6.0, 'max': 7.0},
    'soil_nutrients': {'N': 50, 'P': 30, 'K': 40},
    'temperature_range': {'min': 15, 'max': 24},
    'annual_rainfall_mm': {'min': 800, 'max': 1200},
    'water_ph': {'min': 6.5, 'max': 7.0},
    'sunlight_hours_per_day': {'min': 6, 'max': 8},
    'humidity_range_percent': {'min': 60, 'max': 80},
    'altitude_m': {'min': 600, 'max': 1000},
    'wind_conditions_kmh': {'speed': 5, 'direction': 'NW'}
 }

}
